"""empty message

Revision ID: 084f516beba3
Revises: 52cc8fc27ddd
Create Date: 2018-02-24 21:57:19.344423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '084f516beba3'
down_revision = '52cc8fc27ddd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demandcol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('demand_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('addtime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['demand_id'], ['demand.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_demandcol_addtime'), 'demandcol', ['addtime'], unique=False)
    op.create_table('democol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('demo_id', sa.Integer(), nullable=True),
    sa.Column('enterprise_id', sa.Integer(), nullable=True),
    sa.Column('addtime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['demo_id'], ['demo.id'], ),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprise.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_democol_addtime'), 'democol', ['addtime'], unique=False)
    op.create_table('usercol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('object', sa.Boolean(), nullable=True),
    sa.Column('enterprise_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('addtime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['enterprise_id'], ['demand.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usercol_addtime'), 'usercol', ['addtime'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usercol_addtime'), table_name='usercol')
    op.drop_table('usercol')
    op.drop_index(op.f('ix_democol_addtime'), table_name='democol')
    op.drop_table('democol')
    op.drop_index(op.f('ix_demandcol_addtime'), table_name='demandcol')
    op.drop_table('demandcol')
    # ### end Alembic commands ###
