"""empty message

Revision ID: 0e5050c44fd1
Revises: 031802787af5
Create Date: 2018-03-26 16:58:19.910182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e5050c44fd1'
down_revision = '031802787af5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demand_review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('addtime', sa.DateTime(), nullable=True),
    sa.Column('is_big', sa.Boolean(), nullable=True),
    sa.Column('if_is_user_id', sa.Integer(), nullable=True),
    sa.Column('if_is_enterprise_id', sa.Integer(), nullable=True),
    sa.Column('demand_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['demand_id'], ['demand.id'], ),
    sa.ForeignKeyConstraint(['if_is_enterprise_id'], ['enterprise.id'], ),
    sa.ForeignKeyConstraint(['if_is_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_demand_review_addtime'), 'demand_review', ['addtime'], unique=False)
    op.create_index(op.f('ix_demand_review_is_big'), 'demand_review', ['is_big'], unique=False)
    op.create_table('resolve',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('addtime', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('demand_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['demand_id'], ['demand.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resolve_addtime'), 'resolve', ['addtime'], unique=False)
    op.create_table('demand_discuss',
    sa.Column('demand_discusser_id', sa.Integer(), nullable=False),
    sa.Column('demand_discussed_id', sa.Integer(), nullable=False),
    sa.Column('demand_discuss_addtime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['demand_discussed_id'], ['demand_review.id'], ),
    sa.ForeignKeyConstraint(['demand_discusser_id'], ['demand_review.id'], ),
    sa.PrimaryKeyConstraint('demand_discusser_id', 'demand_discussed_id')
    )
    op.create_index(op.f('ix_demand_discuss_demand_discuss_addtime'), 'demand_discuss', ['demand_discuss_addtime'], unique=False)
    op.add_column('demand', sa.Column('picture', sa.Integer(), nullable=True))
    op.add_column('demo', sa.Column('picture', sa.Integer(), nullable=True))
    op.add_column('demo_review', sa.Column('cre_star', sa.Integer(), nullable=True))
    op.add_column('demo_review', sa.Column('qua_star', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('age', sa.String(length=15), nullable=True))
    op.add_column('user', sa.Column('gender', sa.String(length=15), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'gender')
    op.drop_column('user', 'age')
    op.drop_column('demo_review', 'qua_star')
    op.drop_column('demo_review', 'cre_star')
    op.drop_column('demo', 'picture')
    op.drop_column('demand', 'picture')
    op.drop_index(op.f('ix_demand_discuss_demand_discuss_addtime'), table_name='demand_discuss')
    op.drop_table('demand_discuss')
    op.drop_index(op.f('ix_resolve_addtime'), table_name='resolve')
    op.drop_table('resolve')
    op.drop_index(op.f('ix_demand_review_is_big'), table_name='demand_review')
    op.drop_index(op.f('ix_demand_review_addtime'), table_name='demand_review')
    op.drop_table('demand_review')
    # ### end Alembic commands ###
