"""empty message

Revision ID: 4e436fdd333c
Revises: a4b6f6427c23
Create Date: 2018-03-24 09:33:03.415365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e436fdd333c'
down_revision = 'a4b6f6427c23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('demand', sa.Column('star', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('demand', 'star')
    # ### end Alembic commands ###
