"""empty message

Revision ID: 8581679f2f06
Revises: f3759a5eb4f0
Create Date: 2018-04-07 22:26:51.352237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8581679f2f06'
down_revision = 'f3759a5eb4f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('improve',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('qua_score', sa.Integer(), nullable=True),
    sa.Column('cre_score', sa.Integer(), nullable=True),
    sa.Column('com_score', sa.Integer(), nullable=True),
    sa.Column('word_score', sa.Integer(), nullable=True),
    sa.Column('review', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('addtime', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('demo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['demo_id'], ['demo.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_improve_addtime'), 'improve', ['addtime'], unique=False)
    op.add_column('user', sa.Column('fans', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_user_fans'), 'user', ['fans'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_fans'), table_name='user')
    op.drop_column('user', 'fans')
    op.drop_index(op.f('ix_improve_addtime'), table_name='improve')
    op.drop_table('improve')
    # ### end Alembic commands ###
