"""empty message

Revision ID: a4b6f6427c23
Revises: 62a4081ec5bb
Create Date: 2018-03-23 18:55:33.921131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4b6f6427c23'
down_revision = '62a4081ec5bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('democol', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'democol', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'democol', type_='foreignkey')
    op.drop_column('democol', 'user_id')
    # ### end Alembic commands ###
