"""empty message

Revision ID: d09d50174c0c
Revises: 3b07d428cc06
Create Date: 2018-03-18 13:06:48.981776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd09d50174c0c'
down_revision = '3b07d428cc06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('url', table_name='demand')
    op.drop_index('url', table_name='demo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('url', 'demo', ['url'], unique=True)
    op.create_index('url', 'demand', ['url'], unique=True)
    # ### end Alembic commands ###
