"""empty message

Revision ID: f3759a5eb4f0
Revises: 0e5050c44fd1
Create Date: 2018-03-27 12:19:54.067144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3759a5eb4f0'
down_revision = '0e5050c44fd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resolve', sa.Column('com_score', sa.Integer(), nullable=True))
    op.add_column('resolve', sa.Column('cre_score', sa.Integer(), nullable=True))
    op.add_column('resolve', sa.Column('qua_score', sa.Integer(), nullable=True))
    op.add_column('resolve', sa.Column('review', sa.Text(), nullable=True))
    op.add_column('resolve', sa.Column('word_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resolve', 'word_score')
    op.drop_column('resolve', 'review')
    op.drop_column('resolve', 'qua_score')
    op.drop_column('resolve', 'cre_score')
    op.drop_column('resolve', 'com_score')
    # ### end Alembic commands ###
