"""empty message

Revision ID: f576a1f8abc5
Revises: 4e436fdd333c
Create Date: 2018-03-24 14:21:02.134725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f576a1f8abc5'
down_revision = '4e436fdd333c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('recommand_method', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'recommand_method')
    # ### end Alembic commands ###
